Post review linguistic fixes
maciekmm/origami pull request #164
Opened 2021-01-03 12:34 UTC by maciekmm

2021-01-03 13:00 UTC, zemiret requested changes

2021-01-03 13:27 UTC, maciekmm commented on thesis/03-implementation.tex
> +Origuide is a web application. Hence, \tech{Javascript} has been an obvious choice. We have briefly considered \tech{Typescript} as well, but have not used it due to its more enforcing nature, which
The problem is, we don't have enough space to fit an explanation. Maybe we should remove the regret part altogether.

2021-01-03 13:31 UTC, maciekmm commented on thesis/01-vision.tex
>  \subsection{Problem characteristics}
Dictionary crease pattern works for me:  
![image](https://user-images.githubusercontent.com/3267517/103479739-fe015000-4dcf-11eb-801b-a734c06f1749.png)

2021-01-03 14:20 UTC, zemiret commented on thesis/03-implementation.tex
> +Origuide is a web application. Hence, \tech{Javascript} has been an obvious choice. We have briefly considered \tech{Typescript} as well, but have not used it due to its more enforcing nature, which
Yeah, sure.

2021-01-03 14:21 UTC, zemiret commented on thesis/01-vision.tex
>  \subsection{Problem characteristics}
Well, yes. But the format is different. Everywhere else it's uppercase `Figure`. I think it's the use autoref that does that.

2021-01-03 15:25 UTC, maciekmm commented on thesis/01-vision.tex
>  \subsection{Problem characteristics}
That's fixed. Thought you had "??" there.

2021-01-04 14:25 UTC, zemiret approved these changes

2021-01-04 14:25 UTC, merged