Add liked, solved parameters, introduce factory_boy
maciekmm/origami pull request #91
Opened 2020-10-12 17:24 UTC by zemiret

2020-10-12 18:03 UTC, maciekmm requested changes
:+1: for introducing faker_boy
:+1: for improving the security model
:+1: for new functionality

There are some small changes to be made.

2020-10-12 18:56 UTC, zemiret commented on backend/community/guides/serializers.py
> +    def update(self, instance, validated_data):
I don't think "tangential" works like that. :P

2020-10-14 20:35 UTC, maciekmm approved these changes

2020-10-14 20:35 UTC, maciekmm commented on backend/community/guides/permissions.py
> +        return bool(request.user and request.user.is_authenticated) or\
`request.user is not None` sounds better than implicit-casting to bool

2020-10-15 17:35 UTC, merged